services:
  pgdb:
    image: "postgres:13.2"
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-postgres}
      POSTGRES_DB: ${DATABASE_NAME-postgres}
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nominal_api
    environment:
      DB_USER: ${POSTGRES_USER-postgres}
      DB_PASSWORD: ${POSTGRES_PASSWORD-postgres}
      DB_HOST: pgdb
      DB_PORT: 5432
      DB_NAME: ${DATABASE_NAME-postgres}
    volumes:
      - ./app:/opt/app
      - ./migrations:/opt/app/migrations
      - ./alembic.ini:/opt/app/alembic.ini
    ports:
      - "8000:8000"
    depends_on:
      - pgdb

volumes:
  postgres_db:
